# Generated by Django 6.0.3 on 2026-04-03 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='more_description',
            field=models.TextField(blank=True, help_text='Additional detailed description for the product'),
        ),
        migrations.AddField(
            model_name='product',
            name='specifications',
            field=models.TextField(blank=True, help_text='Product specifications and technical details'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_status',
            field=models.CharField(blank=True, help_text="Current stock availability status (e.g., 'In Stock', 'Out of Stock', 'Limited Stock')", max_length=100),
        ),
    ]
